name: Copy to Documentation Repo
on: [push]
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Copycat
      uses: ./.github/actions/copycat-action
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        dst_owner: newaetech
        dst_repo_name: documentation-main
        targets: 87C51 ADuCM3029 ATMega1284RFR2 ATSAM4L ATSAML11 ATSAMR21 AURIX AVR CC2538 CEC1702 D2000 EFM32GG11 EFM32TG11 EFR32MG21 EFR32MG21_SOCKET ESP32 K24F K82 LPC1343F MPC57 MPC5Y MSP430 STM32F S6LX9 XMEGA LPC55S69 PSoC62